version: '3.9'
services:

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
      args:
        port: 3000
    restart: on-failure
    volumes:
      - ./server/src:/app
    ports:
      - 3000:3000
    networks:
      - bunjs
    logging:
      options:
        max-size: 10m


volumes: {}
networks:
  bunjs:
